[env]
_.file = ".env"
_.path = [".bin"]

[tools]
amp = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
go = "latest"
goreleaser = "latest"
node = "22"
"npm:aws-cdk" = "latest"
golangci-lint = "latest"
shellcheck = "latest"
shfmt = "latest"
1password-cli = "latest"

